/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class database_DatabaseWrapper */

#ifndef _Included_database_DatabaseWrapper
#define _Included_database_DatabaseWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     database_DatabaseWrapper
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_database_DatabaseWrapper_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     database_DatabaseWrapper
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_database_DatabaseWrapper_getName
  (JNIEnv *, jobject);

/*
 * Class:     database_DatabaseWrapper
 * Method:    isChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_database_DatabaseWrapper_isChanged
  (JNIEnv *, jobject);

/*
 * Class:     database_DatabaseWrapper
 * Method:    setFilePath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_database_DatabaseWrapper_setFilePath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     database_DatabaseWrapper
 * Method:    getFilePath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_database_DatabaseWrapper_getFilePath
  (JNIEnv *, jobject);

/*
 * Class:     database_DatabaseWrapper
 * Method:    setChange
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_database_DatabaseWrapper_setChange
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     database_DatabaseWrapper
 * Method:    executeQuery
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_database_DatabaseWrapper_executeQuery
  (JNIEnv *, jobject, jstring);

/*
 * Class:     database_DatabaseWrapper
 * Method:    test
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_database_DatabaseWrapper_test
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     database_DatabaseWrapper
 * Method:    loadDatabase
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_database_DatabaseWrapper_loadDatabase
  (JNIEnv *, jobject, jstring);

/*
 * Class:     database_DatabaseWrapper
 * Method:    exportToSQL
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_database_DatabaseWrapper_exportToSQL
  (JNIEnv *, jobject, jstring);

/*
 * Class:     database_DatabaseWrapper
 * Method:    exportToCustom
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_database_DatabaseWrapper_exportToCustom
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
